### ISSUE TITLE
FSWatcher Error on `yarn start`

### ISSUE THREAD

**Issue by fredfortier** [kangarang/tcr-ui#109]
Just cloned from the master branch and ran `yarn`. I'm using Fedora.
```
$ node --version
v8.11.4
$ yarn --version
1.9.4
$ yarn start
```
```
Starting the development server...

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: watch /home/.../Code/Sandbox/tcr-ui/public ENOSPC
    at _errnoException (util.js:992:11)
    at FSWatcher.start (fs.js:1382:19)
    at Object.fs.watch (fs.js:1408:11)
    at createFsWatchInstance (/home/.../Code/Sandbox/tcr-ui/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/.../Code/Sandbox/tcr-ui/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/.../Code/Sandbox/tcr-ui/node_modules/chokidar/lib/nodefs-handler.js:228:14)
```

**Comment by fredfortier** [comment]
The workaround suggested in this thread works for me: https://github.com/facebook/jest/issues/3254.
